(* FeynCalc script generated by HEPTAPOD/Diagrammatica *)
(* Process: f1 -> S f2bar *)
(* Process type: DECAY_1TO2 *)

<< FeynCalc`

(* Mass definitions — symbolic (no numerical values assigned) *)
(* Masses: mf1, mS, mf2bar *)

(* Step 1: Amplitude for f1 -> S f2bar *)
amp = SpinorV[p2, mf2bar] . (I ((gS) + (gP) GA[5])) . SpinorU[p, mf1];

(* Step 2: Square the amplitude *)
ampCC = ComplexConjugate[amp];
ampCC = ampCC /. {gS -> Conjugate[gS], gP -> Conjugate[gP]};
ampSq = amp ampCC;

(* Step 3: Spin and polarization sums *)
ampSq = FermionSpinSum[ampSq];

(* Step 4: Evaluate traces and contract *)
ampSq = DiracSimplify[ampSq] // Contract // Simplify;

(* Step 5: Kinematics — rest frame of parent *)
(* p = (mf1, 0, 0, 0),  p1 + p2 = p *)
FCClearScalarProducts[];
ScalarProduct[p, p] = mf1^2;
ScalarProduct[p1, p1] = mS^2;
ScalarProduct[p2, p2] = mf2bar^2;
ScalarProduct[p, p1] = (mf1^2 + mS^2 - mf2bar^2)/2;
ScalarProduct[p, p2] = (mf1^2 - mS^2 + mf2bar^2)/2;
ScalarProduct[p1, p2] = (mf1^2 - mS^2 - mf2bar^2)/2;
ampSqKin = ampSq // Simplify;

(* Step 6: Partial decay width *)
(* Gamma = pMag / (8 pi M^2) * (1/nInit) * |M|^2 * colorFactor / symmetryFactor *)
pMag = Sqrt[(mf1^2 - (mS + mf2bar)^2)(mf1^2 - (mS - mf2bar)^2)] / (2 mf1);
nInit = 2;
colorFactor = 1;
symmetryFactor = 1;
width = pMag / (8 Pi mf1^2) * (1/nInit) * ampSqKin * colorFactor / symmetryFactor;
width = width // Simplify;

(* Step 7: Symbolic extraction (no numerical evaluation) *)

(* Squared amplitude after kinematics *)
Print["SYMBOLIC_RESULT[ampSq]: ", ampSqKin];
Print["LATEX_RESULT[ampSq]: ", ToString[TeXForm[ampSqKin]]];

(* Decay width — symbolic only *)
Print["SYMBOLIC_RESULT[width]: ", width];
Print["LATEX_RESULT[width]: ", ToString[TeXForm[width]]];
Print["STATUS: complete"];
