(* SimplifyResultBatch — generated by HEPTAPOD/Diagrammatica *)

(* Load the expression *)
expr = -1/24*(Sqrt[(-(mf - mfbar)^2 + mV^2)*(-(mf + mfbar)^2 + mV^2)]*(gA*(mf^4 + mfbar^4 + 6*mf*mfbar*mV^2 + mfbar^2*mV^2 - 2*mV^4 + mf^2*(-2*mfbar^2 + mV^2))*Conjugate[gA] + gV*(mf^4 + mfbar^4 - 6*mf*mfbar*mV^2 + mfbar^2*mV^2 - 2*mV^4 + mf^2*(-2*mfbar^2 + mV^2))*Conjugate[gV]))/(mV^5*Pi);

(* Apply substitutions *)
expr = expr /. {mf -> 0, mfbar -> 0};

(* Simplify with assumptions *)
expr = Assuming[{mV > 0}, FullSimplify[expr]];

(* Output *)
Print["SYMBOLIC_RESULT[simplified]: ", expr];
Print["LATEX_RESULT[simplified]: ", ToString[TeXForm[expr]]];
Print["STATUS: complete"];