(* SimplifyResultBatch — generated by HEPTAPOD/Diagrammatica *)

(* Load the expression *)
expr = (g*Sqrt[(mS^2 - (mV1 - mV2)^2)*(mS^2 - (mV1 + mV2)^2)]*(mS^4 + mV1^4 + 4*mV1^2*mV2^2 + mV2^4 - 2*mS^2*(mV1^2 + mV2^2))*Conjugate[g])/(8*mS^3*Pi);

(* Apply substitutions *)
expr = expr /. {mV2 -> mV1};

(* Simplify with assumptions *)
expr = Assuming[{mS > 2 mV1, mV1 > 0}, FullSimplify[expr]];

(* Output *)
Print["SYMBOLIC_RESULT[simplified]: ", expr];
Print["LATEX_RESULT[simplified]: ", ToString[TeXForm[expr]]];
Print["STATUS: complete"];