(* SimplifyResultBatch — generated by HEPTAPOD/Diagrammatica *)

(* Load the expression *)
expr = -1/16*(Sqrt[(-(mf - mfbar)^2 + mS^2)*(-(mf + mfbar)^2 + mS^2)]*((2*gR*mf*mfbar + gL*(mf^2 + mfbar^2 - mS^2))*Conjugate[gL] + (2*gL*mf*mfbar + gR*(mf^2 + mfbar^2 - mS^2))*Conjugate[gR]))/(mS^3*Pi);

(* Apply substitutions *)
expr = expr /. {mf -> 0, mfbar -> 0};

(* Simplify *)
expr = FullSimplify[expr];

(* Output *)
Print["SYMBOLIC_RESULT[simplified]: ", expr];
Print["LATEX_RESULT[simplified]: ", ToString[TeXForm[expr]]];
Print["STATUS: complete"];