(* SimplifyResultBatch — generated by HEPTAPOD/Diagrammatica *)

(* Load the expression *)
expr = -1/8*(Sqrt[(-(mf - mfbar)^2 + mS^2)*(-(mf + mfbar)^2 + mS^2)]*(gP*(mf^2 - 2*mf*mfbar + mfbar^2 - mS^2)*Conjugate[gP] + gS*(mf^2 + 2*mf*mfbar + mfbar^2 - mS^2)*Conjugate[gS]))/(mS^3*Pi);

(* Apply substitutions *)
expr = expr /. {mfbar -> mf};

(* Simplify with assumptions *)
expr = Assuming[{mS > 2 mf, mf > 0}, FullSimplify[expr]];

(* Output *)
Print["SYMBOLIC_RESULT[simplified]: ", expr];
Print["LATEX_RESULT[simplified]: ", ToString[TeXForm[expr]]];
Print["STATUS: complete"];