(* SimplifyResultBatch — generated by HEPTAPOD/Diagrammatica *)

(* Load the expression *)
expr = (g*Sqrt[(mV^2 - (mV1 - mV2)^2)*(mV^2 - (mV1 + mV2)^2)]*(mV^8 - 4*mV^6*(mV1^2 + mV2^2) + (mV1^2 - mV2^2)^2*(mV1^4 + 10*mV1^2*mV2^2 + mV2^4) + 2*mV^4*(3*mV1^4 + 8*mV1^2*mV2^2 + 3*mV2^4) - 4*mV^2*(mV1^6 + 5*mV1^4*mV2^2 + 5*mV1^2*mV2^4 + mV2^6))*Conjugate[g])/(192*mV^5*mV1^2*mV2^2*Pi);

(* Apply substitutions *)
expr = expr /. {mV2 -> mV1};

(* Simplify with assumptions *)
expr = Assuming[{mV > 2 mV1, mV1 > 0}, FullSimplify[expr]];

(* Output *)
Print["SYMBOLIC_RESULT[simplified]: ", expr];
Print["LATEX_RESULT[simplified]: ", ToString[TeXForm[expr]]];
Print["STATUS: complete"];