(* SimplifyResultBatch — generated by HEPTAPOD/Diagrammatica *)

(* Load the expression *)
expr = (Sqrt[(mf1^2 - (mf2bar - mV)^2)*(mf1^2 - (mf2bar + mV)^2)]*(gA*(mf1^4 + mf2bar^4 - 6*mf1*mf2bar*mV^2 + mf2bar^2*mV^2 - 2*mV^4 + mf1^2*(-2*mf2bar^2 + mV^2))*Conjugate[gA] + gV*(mf1^4 + mf2bar^4 + 6*mf1*mf2bar*mV^2 + mf2bar^2*mV^2 - 2*mV^4 + mf1^2*(-2*mf2bar^2 + mV^2))*Conjugate[gV]))/(16*mf1^3*mV^2*Pi);

(* Apply substitutions *)
expr = expr /. {mf2bar -> 0};

(* Simplify with assumptions *)
expr = Assuming[{mf1 > mV, mV > 0}, FullSimplify[expr]];

(* Output *)
Print["SYMBOLIC_RESULT[simplified]: ", expr];
Print["LATEX_RESULT[simplified]: ", ToString[TeXForm[expr]]];
Print["STATUS: complete"];