(* SimplifyResultBatch — generated by HEPTAPOD/Diagrammatica *)

(* Load the expression *)
expr = (g*Sqrt[(-(mf - mfbar)^2 + mV^2)*(-(mf + mfbar)^2 + mV^2)]*(-2*mf^4 - 2*mfbar^4 + 6*mf*mfbar*mV^2 + mfbar^2*mV^2 + mV^4 + mf^2*(4*mfbar^2 + mV^2))*Conjugate[g])/(24*mV^3*Pi);

(* Apply substitutions *)
expr = expr /. {mf -> 0, mfbar -> 0};

(* Simplify with assumptions *)
expr = Assuming[{mV > 0}, FullSimplify[expr]];

(* Output *)
Print["SYMBOLIC_RESULT[simplified]: ", expr];
Print["LATEX_RESULT[simplified]: ", ToString[TeXForm[expr]]];
Print["STATUS: complete"];