(* SimplifyResultBatch — generated by HEPTAPOD/Diagrammatica *)

(* Load the expression *)
expr = (g*((-(mS1 - mS2)^2 + mV^2)*(-(mS1 + mS2)^2 + mV^2))^(3/2)*Conjugate[g])/(48*mV^5*Pi);

(* Apply substitutions *)
expr = expr /. {mS2 -> mS1};

(* Simplify with assumptions *)
expr = Assuming[{mV > 2 mS1, mS1 > 0}, FullSimplify[expr]];

(* Output *)
Print["SYMBOLIC_RESULT[simplified]: ", expr];
Print["LATEX_RESULT[simplified]: ", ToString[TeXForm[expr]]];
Print["STATUS: complete"];