(* SimplifyResultBatch — generated by HEPTAPOD/Diagrammatica *)

(* Load the expression *)
expr = -1/48*(Sqrt[(-(mf - mfbar)^2 + mV^2)*(-(mf + mfbar)^2 + mV^2)]*((-6*gR*mf*mfbar*mV^2 + gL*(mf^4 + mfbar^4 + mfbar^2*mV^2 - 2*mV^4 + mf^2*(-2*mfbar^2 + mV^2)))*Conjugate[gL] + (-6*gL*mf*mfbar*mV^2 + gR*(mf^4 + mfbar^4 + mfbar^2*mV^2 - 2*mV^4 + mf^2*(-2*mfbar^2 + mV^2)))*Conjugate[gR]))/(mV^5*Pi);

(* Apply substitutions *)
expr = expr /. {mfbar -> mf};

(* Simplify with assumptions *)
expr = Assuming[{mV > 2 mf, mf > 0}, FullSimplify[expr]];

(* Output *)
Print["SYMBOLIC_RESULT[simplified]: ", expr];
Print["LATEX_RESULT[simplified]: ", ToString[TeXForm[expr]]];
Print["STATUS: complete"];