(* SimplifyResultBatch — generated by HEPTAPOD/Diagrammatica *)

(* Load the expression *)
expr = (g*Sqrt[(mS^2 - (mS1 - mS2)^2)*(mS^2 - (mS1 + mS2)^2)]*Conjugate[g])/(16*mS^3*Pi);

(* Apply substitutions *)
expr = expr /. {mS2 -> mS1};

(* Simplify with assumptions *)
expr = Assuming[{mS > 2 mS1, mS1 > 0}, FullSimplify[expr]];

(* Output *)
Print["SYMBOLIC_RESULT[simplified]: ", expr];
Print["LATEX_RESULT[simplified]: ", ToString[TeXForm[expr]]];
Print["STATUS: complete"];