(* FeynCalc script generated by HEPTAPOD/Diagrammatica *)
(* Process: V -> f fbar *)
(* Process type: DECAY_1TO2 *)

<< FeynCalc`

(* Mass definitions — symbolic (no numerical values assigned) *)
(* Masses: mV, mf, mfbar *)

(* Step 1: Amplitude for V -> f fbar *)
amp = PolarizationVector[p, mu0] SpinorUBar[p1, mf] . (I ((gL) GA[7] + (gR) GA[6]) . DiracSigma[GA[mu0], GA[nuT]] FV[p, nuT]) . SpinorV[p2, mfbar];

(* Step 2: Square the amplitude *)
ampCC = ComplexConjugate[amp];
ampCC = ampCC /. {gL -> Conjugate[gL], gR -> Conjugate[gR]};
ampSq = amp ampCC;

(* Step 3: Spin and polarization sums *)
ampSq = FermionSpinSum[ampSq];
ampSq = DoPolarizationSums[ampSq, p];

(* Step 4: Evaluate traces and contract *)
ampSq = DiracSimplify[ampSq] // Contract // Simplify;

(* Step 5: Kinematics — rest frame of parent *)
(* p = (mV, 0, 0, 0),  p1 + p2 = p *)
FCClearScalarProducts[];
ScalarProduct[p, p] = mV^2;
ScalarProduct[p1, p1] = mf^2;
ScalarProduct[p2, p2] = mfbar^2;
ScalarProduct[p, p1] = (mV^2 + mf^2 - mfbar^2)/2;
ScalarProduct[p, p2] = (mV^2 - mf^2 + mfbar^2)/2;
ScalarProduct[p1, p2] = (mV^2 - mf^2 - mfbar^2)/2;
ampSqKin = ampSq // Simplify;

(* Step 6: Partial decay width *)
(* Gamma = pMag / (8 pi M^2) * (1/nInit) * |M|^2 * colorFactor / symmetryFactor *)
pMag = Sqrt[(mV^2 - (mf + mfbar)^2)(mV^2 - (mf - mfbar)^2)] / (2 mV);
nInit = 3;
colorFactor = 1;
symmetryFactor = 1;
width = pMag / (8 Pi mV^2) * (1/nInit) * ampSqKin * colorFactor / symmetryFactor;
width = width // Simplify;

(* Step 7: Symbolic extraction (no numerical evaluation) *)

(* Squared amplitude after kinematics *)
Print["SYMBOLIC_RESULT[ampSq]: ", ampSqKin];
Print["LATEX_RESULT[ampSq]: ", ToString[TeXForm[ampSqKin]]];

(* Decay width — symbolic only *)
Print["SYMBOLIC_RESULT[width]: ", width];
Print["LATEX_RESULT[width]: ", ToString[TeXForm[width]]];
Print["STATUS: complete"];
