(* FeynCalc script generated by HEPTAPOD/Diagrammatica *)
(* Process: V -> S1 S2 *)
(* Process type: DECAY_1TO2 *)

<< FeynCalc`

(* Mass definitions — symbolic (no numerical values assigned) *)
(* Masses: mV, mS1, mS2 *)

(* Step 1: Amplitude for V -> S1 S2 *)
amp = I (g) PolarizationVector[p, mu1] FVD[p1 - p2, mu1];

(* Step 2: Square the amplitude *)
ampCC = ComplexConjugate[amp];
ampCC = ampCC /. {g -> Conjugate[g]};
ampSq = amp ampCC;

(* Step 3: Spin and polarization sums *)
ampSq = DoPolarizationSums[ampSq, p];

(* Step 4: Evaluate traces and contract *)
ampSq = DiracSimplify[ampSq] // Contract // Simplify;

(* Step 5: Kinematics — rest frame of parent *)
(* p = (mV, 0, 0, 0),  p1 + p2 = p *)
FCClearScalarProducts[];
ScalarProduct[p, p] = mV^2;
ScalarProduct[p1, p1] = mS1^2;
ScalarProduct[p2, p2] = mS2^2;
ScalarProduct[p, p1] = (mV^2 + mS1^2 - mS2^2)/2;
ScalarProduct[p, p2] = (mV^2 - mS1^2 + mS2^2)/2;
ScalarProduct[p1, p2] = (mV^2 - mS1^2 - mS2^2)/2;
ampSqKin = ampSq // Simplify;

(* Step 6: Partial decay width *)
(* Gamma = pMag / (8 pi M^2) * (1/nInit) * |M|^2 * colorFactor / symmetryFactor *)
pMag = Sqrt[(mV^2 - (mS1 + mS2)^2)(mV^2 - (mS1 - mS2)^2)] / (2 mV);
nInit = 3;
colorFactor = 1;
symmetryFactor = 1;
width = pMag / (8 Pi mV^2) * (1/nInit) * ampSqKin * colorFactor / symmetryFactor;
width = width // Simplify;

(* Step 7: Symbolic extraction (no numerical evaluation) *)

(* Squared amplitude after kinematics *)
Print["SYMBOLIC_RESULT[ampSq]: ", ampSqKin];
Print["LATEX_RESULT[ampSq]: ", ToString[TeXForm[ampSqKin]]];

(* Decay width — symbolic only *)
Print["SYMBOLIC_RESULT[width]: ", width];
Print["LATEX_RESULT[width]: ", ToString[TeXForm[width]]];
Print["STATUS: complete"];
