"""
# enumerate_and_rank.py is a part of the HEPTAPOD package.
# Copyright (C) 2026 HEPTAPOD authors (see AUTHORS for details).
# HEPTAPOD is licensed under the GNU GPL v3 or later, see LICENSE for details.
# Please respect the MCnet Guidelines, see GUIDELINES for details.

High-level function for enumerating and ranking Feynman diagrams.

This module provides a convenient interface for the complete workflow:
enumerate diagrams -> convert to HEPTAPOD format -> validate -> rank by NDA.
"""

from typing import List, Dict, Any, Optional, Callable
from dataclasses import dataclass
import sys

try:
    from .feyngraph_interface import FeynGraphInterface
    from .diagram_converter import DiagramConverter
    from .ranking import DiagramRanker, RankedDiagram
except ImportError:
    from feyngraph_interface import FeynGraphInterface
    from diagram_converter import DiagramConverter
    from ranking import DiagramRanker, RankedDiagram

# Import HEPTAPOD types
try:
    from pathlib import Path
    TOOL_DIR = Path(__file__).resolve().parent
    REPO_ROOT = TOOL_DIR.parent.parent
    if str(REPO_ROOT) not in sys.path:
        sys.path.insert(0, str(REPO_ROOT))
    from tools.nda.simple_diagram import Diagram
except ImportError:
    pass


@dataclass
class EnumerationResult:
    """
    Results from diagram enumeration and ranking.

    Attributes:
        ranked_diagrams: List of RankedDiagram objects (sorted by rank)
        fg_diagrams: Original FeynGraph diagram objects (for visualization)
        n_generated: Number of diagrams generated by FeynGraph
        n_converted: Number successfully converted to HEPTAPOD format
        n_valid: Number passing validation
        process_string: Human-readable process description
        errors: List of error messages (if any)
        warnings: List of warning messages
        _diagram_to_fg_idx: Internal mapping from Diagram object id to fg_diagram index
    """
    ranked_diagrams: List[RankedDiagram]
    fg_diagrams: List[Any]  # Original FeynGraph diagrams for visualization
    n_generated: int
    n_converted: int
    n_valid: int
    process_string: str
    errors: List[str]
    warnings: List[str]
    _diagram_to_fg_idx: Dict[int, int] = None  # Maps id(diagram) -> fg_diagrams index

    @property
    def diagrams(self) -> List[Any]:
        """Get the HEPTAPOD Diagram objects from ranked diagrams."""
        return [rd.diagram for rd in self.ranked_diagrams]

    def get_fg_diagram(self, ranked_diagram: RankedDiagram) -> Any:
        """
        Get the original FeynGraph diagram for a RankedDiagram.

        Args:
            ranked_diagram: A RankedDiagram from ranked_diagrams

        Returns:
            The corresponding FeynGraph diagram object, or None if not found
        """
        if self._diagram_to_fg_idx is None:
            return None
        idx = self._diagram_to_fg_idx.get(id(ranked_diagram.diagram))
        if idx is not None and idx < len(self.fg_diagrams):
            return self.fg_diagrams[idx]
        return None

    def summary(self) -> str:
        """Generate a human-readable summary."""
        lines = [
            f"Process: {self.process_string}",
            f"Diagrams generated: {self.n_generated}",
            f"Successfully converted: {self.n_converted}",
            f"Passed validation: {self.n_valid}",
        ]

        if self.errors:
            lines.append(f"Errors: {len(self.errors)}")
        if self.warnings:
            lines.append(f"Warnings: {len(self.warnings)}")

        if self.ranked_diagrams:
            lines.append(f"\nTop-ranked diagram:")
            top = self.ranked_diagrams[0]
            lines.append(f"  Rank: {top.rank}")
            lines.append(f"  Score: {top.ranking_info.score:.6f}")
            lines.append(f"  {top.ranking_info.explanation}")
            if top.width_gev:
                lines.append(f"  Width: {top.width_gev:.3e} GeV")

        return "\n".join(lines)

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return {
            "process": self.process_string,
            "n_generated": self.n_generated,
            "n_converted": self.n_converted,
            "n_valid": self.n_valid,
            "errors": self.errors,
            "warnings": self.warnings,
            "ranked_diagrams": [
                {
                    "rank": rd.rank,
                    "score": rd.ranking_info.score,
                    "explanation": rd.ranking_info.explanation,
                    "topology": rd.diagram.topology,
                    "couplings": rd.diagram.couplings,
                    "width_gev": rd.width_gev,
                    "width_latex": rd.width_latex,
                }
                for rd in self.ranked_diagrams
            ]
        }


def enumerate_and_rank_diagrams(
    initial_particles: List[str],
    final_particles: List[str],
    max_loop_order: int = 0,
    model: str = "SM",
    calculate_widths: bool = False,
    progress_callback: Optional[Callable[[str], None]] = None,
    **feyngraph_kwargs
) -> EnumerationResult:
    """
    Enumerate and rank Feynman diagrams for a given process.

    This is the main high-level function that combines:
    1. FeynGraph diagram generation
    2. Conversion to HEPTAPOD format
    3. Validation
    4. NDA-based ranking

    Args:
        initial_particles: Initial state particles (HEPTAPOD notation)
                         e.g., ["H"], ["mu-"], ["e+", "e-"]
        final_particles: Final state particles (HEPTAPOD notation)
                       e.g., ["b", "bbar"], ["e-", "gamma"]
        max_loop_order: Maximum loop order (0=tree, 1=1-loop, etc.)
        model: Model to use ("SM" for Standard Model, or path to UFO)
        calculate_widths: Whether to calculate NDA width estimates
        progress_callback: Optional function to call with progress messages
                         Useful for showing iterative output to users
        **feyngraph_kwargs: Additional arguments passed to FeynGraph

    Returns:
        EnumerationResult with ranked diagrams and statistics

    Examples:
        >>> # Basic usage
        >>> result = enumerate_and_rank_diagrams(["H"], ["b", "bbar"])
        >>> print(result.summary())

        >>> # With progress output
        >>> def show_progress(msg):
        ...     print(f"[Progress] {msg}")
        >>> result = enumerate_and_rank_diagrams(
        ...     ["H"], ["b", "bbar"],
        ...     progress_callback=show_progress
        ... )

        >>> # Access ranked diagrams
        >>> for rd in result.ranked_diagrams[:5]:
        ...     print(f"Rank {rd.rank}: {rd.ranking_info.explanation}")
    """
    def report(msg: str):
        """Helper to report progress."""
        if progress_callback:
            progress_callback(msg)

    errors = []
    warnings = []

    # Format process string
    initial_str = " + ".join(initial_particles)
    final_str = " + ".join(final_particles)
    process_string = f"{initial_str} → {final_str}"

    report(f"Enumerating diagrams for: {process_string}")
    report(f"Loop order: {max_loop_order}")

    # Step 1: Generate diagrams with FeynGraph
    try:
        report("Step 1/4: Generating diagrams with FeynGraph...")
        interface = FeynGraphInterface(model)
        fg_diagrams = interface.enumerate_diagrams(
            initial_particles,
            final_particles,
            max_loop_order,
            **feyngraph_kwargs
        )
        n_generated = len(fg_diagrams)
        report(f"✓ Generated {n_generated} diagram(s)")
    except Exception as e:
        errors.append(f"FeynGraph enumeration failed: {e}")
        return EnumerationResult(
            ranked_diagrams=[],
            fg_diagrams=[],
            n_generated=0,
            n_converted=0,
            n_valid=0,
            process_string=process_string,
            errors=errors,
            warnings=warnings
        )

    # Step 2: Convert to HEPTAPOD format
    report("Step 2/4: Converting to HEPTAPOD Diagram format...")
    converter = DiagramConverter()
    diagrams = []
    diagram_to_fg_idx = {}  # Maps id(diagram) -> fg_diagrams index

    for i, fg_diagram in enumerate(fg_diagrams):
        try:
            diagram = converter.convert(fg_diagram)
            diagram_to_fg_idx[id(diagram)] = i  # Track mapping before appending
            diagrams.append(diagram)
            report(f"  Converted diagram {i+1}/{n_generated}")
        except Exception as e:
            errors.append(f"Conversion failed for diagram {i+1}: {e}")

    n_converted = len(diagrams)
    report(f"✓ Converted {n_converted}/{n_generated} diagrams")

    if n_converted == 0:
        return EnumerationResult(
            ranked_diagrams=[],
            fg_diagrams=fg_diagrams,
            n_generated=n_generated,
            n_converted=0,
            n_valid=0,
            process_string=process_string,
            errors=errors,
            warnings=warnings,
            _diagram_to_fg_idx={}
        )

    # Step 3: Validate diagrams
    report("Step 3/4: Validating diagrams...")
    n_valid = 0
    for i, diagram in enumerate(diagrams):
        is_valid, diag_warnings = diagram.validate()
        if is_valid:
            n_valid += 1
        else:
            warnings.append(f"Diagram {i+1} validation failed")
        for w in diag_warnings:
            warnings.append(f"Diagram {i+1}: {w}")

    report(f"✓ {n_valid}/{n_converted} diagrams passed validation")
    if warnings:
        report(f"  ({len(warnings)} warning(s))")

    # Step 4: Rank diagrams
    report("Step 4/4: Ranking diagrams by NDA criteria...")
    ranker = DiagramRanker(calculate_nda=calculate_widths)
    ranked = ranker.rank(diagrams)

    report(f"✓ Ranked {len(ranked)} diagrams")
    if ranked:
        top = ranked[0]
        report(f"  Top diagram: Score={top.ranking_info.score:.3f}, {top.ranking_info.explanation}")

    report("\n✓ Complete!")

    return EnumerationResult(
        ranked_diagrams=ranked,
        fg_diagrams=fg_diagrams,
        n_generated=n_generated,
        n_converted=n_converted,
        n_valid=n_valid,
        process_string=process_string,
        errors=errors,
        warnings=warnings,
        _diagram_to_fg_idx=diagram_to_fg_idx
    )


def enumerate_and_rank_diagrams_simple(
    process: str,
    max_loop_order: int = 0,
    model: str = "SM",
    progress_callback: Optional[Callable[[str], None]] = None
) -> EnumerationResult:
    """
    Simplified interface using a process string.

    Args:
        process: Process string like "H -> b bbar" or "mu- -> e- nu_ebar nu_mu"
        max_loop_order: Maximum loop order
        model: Model to use
        progress_callback: Optional progress callback

    Returns:
        EnumerationResult

    Examples:
        >>> result = enumerate_and_rank_diagrams_simple("H -> b bbar")
        >>> result = enumerate_and_rank_diagrams_simple("t -> b W+")
    """
    # Parse process string
    if "->" not in process:
        raise ValueError(
            f"Process string must contain '->': '{process}'\n"
            f"Example: 'H -> b bbar'"
        )

    initial_str, final_str = process.split("->")
    initial_particles = [p.strip() for p in initial_str.strip().split()]
    final_particles = [p.strip() for p in final_str.strip().split()]

    return enumerate_and_rank_diagrams(
        initial_particles,
        final_particles,
        max_loop_order,
        model,
        progress_callback=progress_callback
    )


# Convenience alias (avoid 'enumerate' - conflicts with built-in)
enumerate_simple = enumerate_and_rank_diagrams_simple
